### ISSUE TITLE
CLI Yaml Parsing

### ISSUE THREAD

**Issue by jchen42703** [jchen42703/create-fullstack#12]
### CLI Version

```shell
create-fullstack v0.0.1-dev
on linux_amd64
```

### Use Cases

Besides having an interactive CLI UI to select your augmentation options, users should also be able to specify a yaml configuration to run the CLI.

This will be good for standardizing templates for orgs (so everyone can generate the same templates).

### Attempted Solutions

The `internal/configs` have yaml configs, but there is no command integration yet.

### Proposal

Besides having an interactive CLI UI to select your augmentation options, users should also be able to specify a yaml configuration, such as:

```yaml
# Each of the top level sections (ui, api, infra) are optional unless fullstack exists
# Generates everything
# Infra, ui, backend
fullstack:
  output_dir: "./fullstack_app_name"
  payments:
    stripe: true
    paypal: true
  # One of exists or doesn't exist
  # Uses ory
  # Future: auth0
  # Generating auth code took complex and potentially dangerous for this project
  auth:
    username_password:
      # email verification by default
      email_verification: true
      username_is_email: true
      password_validation: true
    social_sign_in:
      google_callback_url: "http://localhost:3000/dashboard"
      facebook_callback_url: "http://localhost:3000/dashboard"
      github_callback_url: "http://localhost:3000/dashboard"

ui:
  output_dir: "./fullstack_app_name/ui"
  # Base template to augment
  # one of:
  # nextjs, nextjs_ory, create_react_app
  # - can support others like angular, vue, svelte gatsby, vite, etc.
  # If not one of those:
  # Check if it's a git url: and git clone
  # If not: throw error
  base: nextjs
  # go, python, javascript, typescript
  lang: typescript
  augment:
    tailwind:
      # one of default, latest or the version number
      # [package-name]@[version-number]
      # Whenever, we run commands, we fix the version numbers as part of the default behavior.
      # But, if you're making a plugin, you should specify the version numebr that works for you.
      version: default
    scss:
      version: default
    styled_components:
      version: default
    # Should be null if lang != javascript/typescript
    # Prettier and eslint required for all js/ts
    husky:
      commitlint:
        version: default
    prettier:
      version: default
    eslint:
      version: default
    # If custom base template, then behavior can vary.
    dockerfile: true
    # If custom base template, then behavior can vary.
    # I.e. circleci, travisci, jenkins, git_workflows
    ci: git_workflows

api:
  output_dir: "./fullstack_app_name/api"
  # Base template to augment
  # one of:
  # default, echo, echo_ory, express, fastify, fastapi
  # - can support others like gin, chi
  # If not one of those:
  # Check if it's a git url: and git clone
  # If not: throw error
  base: echo
  lang: go
  # Not too sure about this option
  db:
    # one of:
    # postgres, mysql, cockroachdb
    sql:
      db_type: postgres
      startup_script: ""
    no_sql:
      mongodb: true
      redis: true
      cassandra: true
      scylladb: true
  augment:
    # js-only
    # husky:
    #   commitlint: true
    # If not javascript/typescript, husky is null
    husky: null
    # anything besides js
    pre_commit:
      lint: true
      # null if you don't want a formatter
      # format: null
      format:
        # Go just has go_fmt
        # Python formatters:
        # yapf, black, pep8
        formatter: black

    # if custom base template, then behavior can vary.
    dockerfile: true
    git:
      issue_templates: true
      pr_templates: true
    # If custom base template, then behavior can vary.
    # I.e. circleci, travisci, jenkins, git_workflows
    ci: git_workflows

# Tentative as of now
infra:
  output_dir: "./fullstack_app_name/infra"
  docker_compose: true
  k8s: true
  nginx: true

  # mysql, postgres
  db_image:
  ui_image:
  api_image:
  domain_name:
  # gcloud/aws/azure
  cloud_provider: gcloud

# Low prio
cli:
api_client:
  # api client sdk
```

The user should be able to run `create_fullstack run "<PATH TO YAML>"` to generate the aforementioned templates.
